name: smilesx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - gpy=1.9.8
  - gpyopt=1.2.5
  - ipykernel
  - keras=2.2.4
  - matplotlib=3.1.0
  - pandas=0.24.2
  - rdkit
  - scikit-learn=0.21.2
  - adjusttext=0.7.3
