name: smilesx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - gpy
  - gpyopt
  - ipykernel
  - tensorflow
  - keras
  - matplotlib
  - pandas
  - rdkit
  - scikit-learn
  - adjusttext
